### ISSUE TITLE
API Discussion

### ISSUE THREAD

**Issue by Spartan322** [firegodjr/Alagaesias-Ancient-Language#1]
I see that a discussion on an API system would probably be best done inside the issue tracker.

This is for that discussion.

Currently I have developed [Spartan322/api](https://github.com/Spartan322/Alagaesias-Ancient-Language/tree/api) as an outline. As far as I've gotten it however, it can now run every possible word from the original WordHandler and more (I have not got wards, which should actually be called object enchantment or something, but it shouldn't be too hard to fix up eventually). Currently, it can be extended very easily, however it has not been opened up to external manipulation (which I can commit in an instant). I'd like to get opinions on this development before I make a PR for it. (also check out [Spartan322/master](https://github.com/Spartan322/Alagaesias-Ancient-Language/tree/master) for my gradle commits, which I might PR first it they are fine with @firegodjr)

**Comment by firegodjr** [comment]
I love it! :D It feels so much cleaner now.

I haven't been able to personally check out all the changes you've made yet (I've been busy with school crap this week and I'm typing this on my phone) but your API is definitely better than my clunky hardcoded system.

As for the Gradle, as long as it doesn't break with Eclipse I have no problem with it. I'll just need to try it out on my laptop first. What exactly are all the benefits of upgrading Gradle? Just faster compiling in general?

**Comment by Spartan322** [comment]
The speed of development and you could sneak a cleaner gradle build (though I never bother with the cleaner file cause it never ends up much cleaner and breaks backwards compatibility) but ehh. Either way, what I did with gradle now allows you to modify a file to entirely change the build instead of modifying the entire build itself. It also makes deobfs and source stuff for addon and extension development easier after I do a single commit of a few additions and some uncommenting. And the release file and deobf and source files now go in a release folder instead of being trapped in an arbitrary spot that is not directly referenced anywhere

Also, nope, it does not break Eclipse at all (though I kind of wish Eclipse didn't need to refresh gradle using a network every time you start it up, but that is a gradle/eclipse issue)

Also, I'll document more of it when I setup the PR. Also, should I setup a PR like tonight or tomorrow for review or do you want to review it first then give me an all clear to then PR? (usually the former option is done on github, but this one I'll let you choose)

Also, I might need to refactor a hell of a lot of shit before I feel comfortable PRing this entire thing

Also, you'd be fine with terminating all the older, non-api code, right?

One more thing: The fatigue and distance needed to be handled by the script objects, but they aren't implemented (well, some spells cause generalized fatigue, but the current implementation doesn't really do much), and I had no real idea how you wanted that to be handled, so I practically left it out for you to do (or tell me what you'd like and I'd provide it). If you do it, I suggest creating a static method which iterates through the selectors in an IWord object, determines the total fatigue, and applies it to the target through the IEnergyProducer useMagic method

We need to fix up the Entity and EntityPlayer IEnergyProducer stuff in the magic.Utilities folder, but I have no idea what to do with that so...

(I'm thinking of giving over all the info in IWords to the useMagic method and just adding a minimal energyRequest parameter that is default for when there is one object one block away)

(Also, I was thinking of adding wrapper interfaces for things you can't modify normally, but I then thought "Ehh, that only happens with Entities and Player entities," and decided, for now at least, there is no point)

**Comment by Spartan322** [comment]
I'll just strip all irrelevant stuff in fact, and I'll refactor and push tonight, then PR my changes tomorrow.

Still need input on how to handle fatigue however, should I leave it up to the interface implementer?

**Comment by firegodjr** [comment]
I've been having trouble getting Forge to cooperate with my clone of your fork, so go ahead and make the PR, then I can get it downloaded and look it over. I'll make a backup branch to keep the old files just for reference in case something goes wrong (I don't know what would. Maybe I'm just a hoarder.)

I'm thinking fatigue should apply based on what word is used, but distance was kind of a side thing that I added in when programming the entity detection, and not entirely necessary now in my opinion. It's doubtful that a player would want to cast spells over distances like Eragon did with the Urgal army, and a spell at that distance could easily be accidental if the spell range was long enough and the player accidentally looks at the horizon, so in normal casting circumstances I don't think distance would apply enough to be relevant. Once you send the PR I could go ahead and work on the fatigue handling, but again I'd need to look it over in Eclipse. Reading each file individually in GitHub is a bit difficult to piece together, and I still need to work out the Forge environment stuff for my clone of the fork.

**Comment by Spartan322** [comment]
Alright, I'll refactor tonight, and PR tomorrow then, also, make sure you run `gradlew setupDecompWorkspace` in the cmd, I've made the mistake of not doing that before and it would crash the Eclipse version.

Either way, I feel giving the script instance, selector list, and default fatigue value for one object would probably be the best for the useMagic method instead.

Also, if you want to make a backup branch, might be good to create it now.

So cleanup starts now and then I'll PR.

**Comment by firegodjr** [comment]
Alright. Backup created.

I have copied my Forge environment over and ran `gradlew setupDecompWorkspace` and `gradlew eclipse` before but it didn't seem to change much; loading into the "eclipse" folder with the IDE just loads the eclipse folder from the other Forge environment I copied the files from. I just need to mess with it a bit more to figure out what's causing it.

**Comment by Spartan322** [comment]
If you don't have a gradle eclipse plugin, you should be using the archive file generated at the root. Also, IDK why it is called the eclipse folder, when it is just where minecraft generates the .minecraft folder files like the saves and screenshots. Also `gradlew eclipse` no longer does anything in Forge, it is a deprecated command and is of no more use.

**Comment by Spartan322** [comment]
Would you like me to open up the stuff which allows addon/extension development, or would you want to do that yourself and just PR now?

**Comment by firegodjr** [comment]
I managed to get it working. I just needed a clean eclipse folder from the 1.8 MDK and to resolve some build path issues.

**Comment by firegodjr** [comment]
Go ahead and just PR. I can do that myself.

**Comment by Spartan322** [comment]
ok, #2 is in, everything works as expected.

**Comment by Spartan322** [comment]
#2 has resolved this, closing now.
